/* Public beta engine config — regenerated by engine/publish.sh */
window.NOSPEAKY_CONFIG = {
  apiBase: "https://telecommunications-installed-criterion-survival.trycloudflare.com",
  apiKey: "OiKZ-83NqTzag33lg3858xAyXNMXL3Rv"
};
