#!/usr/bin/env bash
# Restart engine with API key + open a public HTTPS Cloudflare quick tunnel.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

KEY_FILE="$ROOT/engine/.api_key"
if [[ -f "$KEY_FILE" ]]; then
  KEY="$(tr -d '[:space:]' < "$KEY_FILE")"
else
  KEY="$(python3 -c 'import secrets; print(secrets.token_urlsafe(24))')"
  printf '%s\n' "$KEY" > "$KEY_FILE"
  chmod 600 "$KEY_FILE"
fi

# kill old engine on 8788
if lsof -tiTCP:8788 -sTCP:LISTEN >/dev/null 2>&1; then
  lsof -tiTCP:8788 -sTCP:LISTEN | xargs kill 2>/dev/null || true
  sleep 1
fi

export NOSPEAKY_API_KEY="$KEY"
export NOSPEAKY_MODEL="${NOSPEAKY_MODEL:-mlx-community/whisper-small-mlx}"
export NOSPEAKY_MAX_DURATION_SEC="${NOSPEAKY_MAX_DURATION_SEC:-600}"
export NOSPEAKY_JOB_LIMIT_PER_HOUR="${NOSPEAKY_JOB_LIMIT_PER_HOUR:-8}"

nohup .venv/bin/uvicorn engine.server:app --host 127.0.0.1 --port 8788 --app-dir "$ROOT" \
  >"$ROOT/engine/data/engine.log" 2>&1 &
echo $! > "$ROOT/engine/data/engine.pid"
sleep 2
curl -sf "http://127.0.0.1:8788/health" >/dev/null

# kill previous cloudflared if tracked
if [[ -f "$ROOT/engine/data/tunnel.pid" ]]; then
  kill "$(cat "$ROOT/engine/data/tunnel.pid")" 2>/dev/null || true
fi

LOG="$ROOT/engine/data/tunnel.log"
: > "$LOG"
nohup cloudflared tunnel --url http://127.0.0.1:8788 --no-autoupdate >"$LOG" 2>&1 &
echo $! > "$ROOT/engine/data/tunnel.pid"

URL=""
for i in $(seq 1 40); do
  URL=$(grep -oE 'https://[a-zA-Z0-9.-]+\.trycloudflare\.com' "$LOG" | head -1 || true)
  if [[ -n "$URL" ]]; then break; fi
  sleep 0.5
done

if [[ -z "$URL" ]]; then
  echo "Tunnel URL not found. See $LOG"
  exit 1
fi

printf '%s\n' "$URL" > "$ROOT/engine/data/tunnel_url.txt"

# write public site config
cat > "$ROOT/js/config.js" <<EOF
/* Public beta engine config — regenerated by engine/publish.sh */
window.NOSPEAKY_CONFIG = {
  apiBase: "$URL",
  apiKey: "$KEY"
};
EOF

echo "ENGINE_OK key=$KEY"
echo "TUNNEL=$URL"
echo "CONFIG=$ROOT/js/config.js"
